FROM node:13.12.0-albine

# SET WORKING DIRECTORY

WORKDIR /app

#add '/app/node_modules/.bin' to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#INSTALL app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm INSTALL
RUN npm install react-scripts@3.4.1 -g

#add app

COPY . ./

#START APP
cmd ["npm", "start"]